remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: EnlightenAI
description: An intelligent codebase explainer that generates comprehensive tutorials from GitHub repositories
show_downloads: true

github:
  repository_url: https://github.com/Mathews-Tom/EnlightenAI
  zip_url: https://github.com/Mathews-Tom/EnlightenAI/archive/refs/heads/main.zip
  tar_url: https://github.com/Mathews-Tom/EnlightenAI/archive/refs/heads/main.tar.gz

# Navigation
nav:
  - Home: index.md
  - Examples:
    - FastAPI: examples/fastapi/index.md
    - NumPy: examples/numpy/index.md
    - AutoGen: examples/autogen/index.md
  - Documentation:
    - Installation: installation.md
    - Usage: usage.md
    - Configuration: configuration.md
  - About:
    - Contributing: contributing.md
    - License: license.md
